apiVersion: v1
kind: Service
metadata:
  name: service-pyapp
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: pyapp-port
    protocol: TCP
  selector:
    app: pyapp
  type: NodePort
